--------------------------------------------------------------------
--  Purpose: create psa tables
--
--  Revision History:
--  Date     Engineer      Description
--  -------- ------------- ----------------------------------
--  dd/mm/yy
--------------------------------------------------------------------
use role {role};
use database {environment}_plt_rl_snowflake_db;
use schema account_usage;


--
-- transient staging table with no retention days
--

 create or replace transient table query_history_stg (
    ORGANIZATION_NAME VARCHAR(8),
    ACCOUNT_NAME VARCHAR(16777216),
    REGION_NAME VARCHAR(16777216),
    QUERY_ID VARCHAR(16777216),
    QUERY_TEXT VARCHAR(16777216),
    DATABASE_ID VARCHAR(16777216),
    DATABASE_NAME VARCHAR(16777216),
    SCHEMA_ID NUMBER(38,0),
    SCHEMA_NAME VARCHAR(16777216),
    QUERY_TYPE VARCHAR(16777216),
    SESSION_ID NUMBER(38,0),
    USER_NAME VARCHAR(16777216),
    ROLE_NAME VARCHAR(16777216),
    WAREHOUSE_ID NUMBER(38,0),
    WAREHOUSE_NAME VARCHAR(16777216),
    WAREHOUSE_SIZE VARCHAR(16777216),
    WAREHOUSE_TYPE VARCHAR(16777216),
    CLUSTER_NUMBER NUMBER(38,0),
    QUERY_TAG VARCHAR(16777216),
    EXECUTION_STATUS VARCHAR(16777216),
    ERROR_CODE VARCHAR(16777216),
    ERROR_MESSAGE VARCHAR(16777216),
    START_TIME TIMESTAMP_LTZ(6),
    END_TIME TIMESTAMP_LTZ(6),
    TOTAL_ELAPSED_TIME NUMBER(38,0),
    BYTES_SCANNED NUMBER(38,0),
    PERCENTAGE_SCANNED_FROM_CACHE FLOAT,
    BYTES_WRITTEN NUMBER(38,0),
    BYTES_WRITTEN_TO_RESULT NUMBER(38,0),
    BYTES_READ_FROM_RESULT NUMBER(38,0),
    ROWS_PRODUCED NUMBER(38,0),
    ROWS_INSERTED NUMBER(38,0),
    ROWS_UPDATED NUMBER(38,0),
    ROWS_DELETED NUMBER(38,0),
    ROWS_UNLOADED NUMBER(38,0),
    BYTES_DELETED NUMBER(38,0),
    PARTITIONS_SCANNED NUMBER(38,0),
    PARTITIONS_TOTAL NUMBER(38,0),
    BYTES_SPILLED_TO_LOCAL_STORAGE NUMBER(38,0),
    BYTES_SPILLED_TO_REMOTE_STORAGE NUMBER(38,0),
    BYTES_SENT_OVER_THE_NETWORK NUMBER(38,0),
    COMPILATION_TIME NUMBER(38,0),
    EXECUTION_TIME NUMBER(38,0),
    QUEUED_PROVISIONING_TIME NUMBER(38,0),
    QUEUED_REPAIR_TIME NUMBER(38,0),
    QUEUED_OVERLOAD_TIME NUMBER(38,0),
    TRANSACTION_BLOCKED_TIME NUMBER(38,0),
    OUTBOUND_DATA_TRANSFER_CLOUD VARCHAR(16777216),
    OUTBOUND_DATA_TRANSFER_REGION VARCHAR(16777216),
    OUTBOUND_DATA_TRANSFER_BYTES NUMBER(38,0),
    INBOUND_DATA_TRANSFER_CLOUD VARCHAR(16777216),
    INBOUND_DATA_TRANSFER_REGION VARCHAR(16777216),
    INBOUND_DATA_TRANSFER_BYTES NUMBER(38,0),
    LIST_EXTERNAL_FILES_TIME NUMBER(38,0),
    CREDITS_USED_CLOUD_SERVICES FLOAT,
    RELEASE_VERSION VARCHAR(16777216),
    EXTERNAL_FUNCTION_TOTAL_INVOCATIONS NUMBER(38,0),
    EXTERNAL_FUNCTION_TOTAL_SENT_ROWS NUMBER(38,0),
    EXTERNAL_FUNCTION_TOTAL_RECEIVED_ROWS NUMBER(38,0),
    EXTERNAL_FUNCTION_TOTAL_SENT_BYTES NUMBER(38,0),
    EXTERNAL_FUNCTION_TOTAL_RECEIVED_BYTES NUMBER(38,0),
    QUERY_LOAD_PERCENT NUMBER(38,0),
    IS_CLIENT_GENERATED_STATEMENT BOOLEAN
     
    ,dw_file_name                   varchar( 250 )      not null
    ,dw_file_row_no                 number              not null
    ,dw_load_ts                     timestamp_ltz       not null
)
data_retention_time_in_days = 0
copy grants
;

--
-- permanent history table with retention days
--
create or replace table query_history
(
    dw_event_shk                   binary( 20 )        not null,
    
   	ORGANIZATION_NAME VARCHAR(8),
    ACCOUNT_NAME VARCHAR(16777216),
    REGION_NAME VARCHAR(16777216),
    QUERY_ID VARCHAR(16777216),
    QUERY_TEXT VARCHAR(16777216),
    DATABASE_ID VARCHAR(16777216),
    DATABASE_NAME VARCHAR(16777216),
    SCHEMA_ID NUMBER(38,0),
    SCHEMA_NAME VARCHAR(16777216),
    QUERY_TYPE VARCHAR(16777216),
    SESSION_ID NUMBER(38,0),
    USER_NAME VARCHAR(16777216),
    ROLE_NAME VARCHAR(16777216),
    WAREHOUSE_ID NUMBER(38,0),
    WAREHOUSE_NAME VARCHAR(16777216),
    WAREHOUSE_SIZE VARCHAR(16777216),
    WAREHOUSE_TYPE VARCHAR(16777216),
    CLUSTER_NUMBER NUMBER(38,0),
    QUERY_TAG VARCHAR(16777216),
    EXECUTION_STATUS VARCHAR(16777216),
    ERROR_CODE VARCHAR(16777216),
    ERROR_MESSAGE VARCHAR(16777216),
    START_TIME TIMESTAMP_LTZ(6),
    END_TIME TIMESTAMP_LTZ(6),
    TOTAL_ELAPSED_TIME NUMBER(38,0),
    BYTES_SCANNED NUMBER(38,0),
    PERCENTAGE_SCANNED_FROM_CACHE FLOAT,
    BYTES_WRITTEN NUMBER(38,0),
    BYTES_WRITTEN_TO_RESULT NUMBER(38,0),
    BYTES_READ_FROM_RESULT NUMBER(38,0),
    ROWS_PRODUCED NUMBER(38,0),
    ROWS_INSERTED NUMBER(38,0),
    ROWS_UPDATED NUMBER(38,0),
    ROWS_DELETED NUMBER(38,0),
    ROWS_UNLOADED NUMBER(38,0),
    BYTES_DELETED NUMBER(38,0),
    PARTITIONS_SCANNED NUMBER(38,0),
    PARTITIONS_TOTAL NUMBER(38,0),
    BYTES_SPILLED_TO_LOCAL_STORAGE NUMBER(38,0),
    BYTES_SPILLED_TO_REMOTE_STORAGE NUMBER(38,0),
    BYTES_SENT_OVER_THE_NETWORK NUMBER(38,0),
    COMPILATION_TIME NUMBER(38,0),
    EXECUTION_TIME NUMBER(38,0),
    QUEUED_PROVISIONING_TIME NUMBER(38,0),
    QUEUED_REPAIR_TIME NUMBER(38,0),
    QUEUED_OVERLOAD_TIME NUMBER(38,0),
    TRANSACTION_BLOCKED_TIME NUMBER(38,0),
    OUTBOUND_DATA_TRANSFER_CLOUD VARCHAR(16777216),
    OUTBOUND_DATA_TRANSFER_REGION VARCHAR(16777216),
    OUTBOUND_DATA_TRANSFER_BYTES NUMBER(38,0),
    INBOUND_DATA_TRANSFER_CLOUD VARCHAR(16777216),
    INBOUND_DATA_TRANSFER_REGION VARCHAR(16777216),
    INBOUND_DATA_TRANSFER_BYTES NUMBER(38,0), 
    LIST_EXTERNAL_FILES_TIME NUMBER(38,0),
    CREDITS_USED_CLOUD_SERVICES FLOAT,
    RELEASE_VERSION VARCHAR(16777216),
    EXTERNAL_FUNCTION_TOTAL_INVOCATIONS NUMBER(38,0),
    EXTERNAL_FUNCTION_TOTAL_SENT_ROWS NUMBER(38,0),
    EXTERNAL_FUNCTION_TOTAL_RECEIVED_ROWS NUMBER(38,0),
    EXTERNAL_FUNCTION_TOTAL_SENT_BYTES NUMBER(38,0),
    EXTERNAL_FUNCTION_TOTAL_RECEIVED_BYTES NUMBER(38,0),
    QUERY_LOAD_PERCENT NUMBER(38,0),
    IS_CLIENT_GENERATED_STATEMENT BOOLEAN
     
    ,dw_file_name                   varchar(250)      not null
    ,dw_file_row_no                 number              not null
    ,dw_load_ts                     timestamp_ltz       not null
)
data_retention_time_in_days = 1
copy grants
;

